name: Node.js CI
on:
  push:
    branches:
      - master
jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [12.x]
            
        steps:
            - name: Checkout source code
              uses: actions/checkout@v2
            
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                node-version: ${{ matrix.node-version }}
            - name: Cache Node.js modules
              uses: actions/cache@v2
              with:
                # npm cache files are stored in `~/.npm` on Linux/macOS
                path: ~/.npm 
                key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
                restore-keys: |
                    ${{ runner.OS }}-node-
                    ${{ runner.OS }}-
            - name: Install dependencies
              run: npm install
            # - name: Unit tests
            #   run: npm run test
            - name: Build app if present
              run: npm run build --if-present

    deploy:
        needs: build
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Deploy to Heroku
              uses: akhileshns/heroku-deploy@v3.6.8
              with:
                heroku_api_key: ${{secrets.HEROKU_API_KEY}}
                heroku_app_name: ci-cd-nodejs #Must be unique in Heroku
                heroku_email: marwenhanzouli@gmail.com
                branche: master